import pytest
import asyncio
from voice_agent.components.base import PipelineComponent, BaseSourceComponent
from voice_agent.frame.base import TextFrame # assuming this exists from previous read
from voice_agent.events import VoiceAgentEvent, EventType

class MockComponent(PipelineComponent):
    def __init__(self, name):
        super().__init__(name)
        self.processed_frames = []

    async def process_frame(self, frame):
        self.processed_frames.append(frame)
        await self.push(frame)

@pytest.mark.asyncio
async def test_pipeline_chaining():
    comp1 = MockComponent("Comp1")
    comp2 = MockComponent("Comp2")
    
    # link pipeline components
    comp1.set_next(comp2)
    assert comp1.next_component == comp2

    # Provide initial frame
    frame = TextFrame(text="test data")
    await comp1.input_queue.put(frame)

    t1 = asyncio.create_task(comp1.run())
    t2 = asyncio.create_task(comp2.run())

    # Yield control to let event loop process
    await asyncio.sleep(0.1)

    assert len(comp1.processed_frames) == 1
    assert comp1.processed_frames[0] == frame
    
    assert len(comp2.processed_frames) == 1
    assert comp2.processed_frames[0] == frame

    # stop gracefully
    comp1._stop_event.set()
    comp2._stop_event.set()
    
    await asyncio.gather(t1, t2)

@pytest.mark.asyncio
async def test_component_flush_on_cancel():
    comp = MockComponent("Comp3")
    
    for _ in range(5):
        await comp.input_queue.put(TextFrame(text="dummy frame"))
    
    assert comp.input_queue.qsize() == 5
    
    await comp.handle_event(VoiceAgentEvent(type=EventType.CANCEL_PIPELINE))
    assert comp.input_queue.qsize() == 0

@pytest.mark.asyncio
async def test_component_stop_on_session_ended():
    comp = MockComponent("Comp4")
    assert not comp._stop_event.is_set()
    
    await comp.handle_event(VoiceAgentEvent(type=EventType.SESSION_ENDED))
    assert comp._stop_event.is_set()

class MockSourceComponent(BaseSourceComponent):
    async def generate_frames(self):
        for i in range(3):
            await asyncio.sleep(0.01)  # Simulate Network IO
            yield TextFrame(text=f"source frame {i}")

@pytest.mark.asyncio
async def test_source_component_generation():
    source = MockSourceComponent("SourceComp")
    sink = MockComponent("SinkComp")
    
    # Connect source directly to a sink
    source.set_next(sink)
    
    t_source = asyncio.create_task(source.run())
    t_sink = asyncio.create_task(sink.run())
    
    # Wait long enough for the async generator to yield all items and push them
    await asyncio.sleep(0.1)
    
    # Ensure source generator exhausted itself
    assert t_source.done()
    
    # Check if the frames were generated by source and received by sink
    assert len(sink.processed_frames) == 3
    assert sink.processed_frames[0].text == "source frame 0"
    assert sink.processed_frames[2].text == "source frame 2"
    
    # Clean up sink task
    sink._stop_event.set()
    await t_sink
