import os
from pathlib import Path

from dotenv import load_dotenv
from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from voice_agent.components.base import PipelineComponent
from voice_agent.frame import AudioFrame, TextFrame
from voice_agent.pipeline.base import Pipeline
from voice_agent.plugins.tecent.stt import TencentStreamingSTT
from voice_agent.transport.websocket import WebSocketTransport

router = APIRouter()

class EchoComponent(PipelineComponent):
    def __init__(self):
        super().__init__(name="EchoComponent")

    async def process_frame(self, frame):
        # Transparently pass audio frames forward
        if isinstance(frame, AudioFrame):
            await self.push(frame)

@router.websocket("/ws/echo")
async def websocket_echo_endpoint(websocket: WebSocket):
    await websocket.accept()
    
    transport = WebSocketTransport(websocket)
    
    # Get transport input and output components
    input_comp = transport.input
    output_comp = transport.output
    
    # Create the transparent echo component
    echo_comp = EchoComponent()
    
    # Chain components: input -> echo -> output
    input_comp.to(echo_comp).to(output_comp)
    
    # Initialize the pipeline with all components
    pipeline = Pipeline(components=[input_comp, echo_comp, output_comp])
    
    try:
        # Start the pipeline (it will run until SESSION_ENDED is triggered by disconnect)
        await pipeline.run()
    except WebSocketDisconnect:
        pass
    except Exception as e:
        print(f"Pipeline encountered an error: {e}")
    finally:
        # Give pipeline stop a chance if it hasn't successfully cleaned up
        try:
            await pipeline.stop()
        except Exception:
            pass


class ConsolePrintComponent(PipelineComponent):
    def __init__(self):
        super().__init__(name="ConsolePrintComponent")

    async def process_frame(self, frame):
        # We only care about TextFrames generated by STT
        if isinstance(frame, TextFrame):
            print(f"\n📝 [Transcription]: {frame.text}")


@router.websocket("/ws/transcribe")
async def websocket_transcribe_endpoint(websocket: WebSocket):
    await websocket.accept()
    
    transport = WebSocketTransport(websocket)
    input_comp = transport.input
    
    load_dotenv(Path.home() / ".env")
    # Instantiate the Tencent STT engine (using the credentials from your plugin)
    base_url = os.getenv("TENCENT_ASR_BASE_URL")
    part_url = os.getenv("TENCENT_ASR_PART_URL")
    secret_id = os.getenv("TENCENT_ASR_SECRET_ID")
    secret_key = os.getenv("TENCENT_ASR_SECRET_KEY")
    
    if not all([base_url, part_url, secret_id, secret_key]):
        raise ValueError("Tencent ASR credentials are not fully set in the environment variables.")
    
    stt_comp = TencentStreamingSTT(
        base_url=base_url,
        part_url=part_url,
        secret_id=secret_id,
        secret_key=secret_key,
        vad_silence=1000
    )
    
    # Create the terminal print component
    print_comp = ConsolePrintComponent()
    
    # Chain components: WebSocket Input (AudioFrame) -> STT (TextFrame) -> Console Printer
    input_comp.to(stt_comp).to(print_comp)
    
    # Initialize the pipeline with all components
    pipeline = Pipeline(components=[input_comp, stt_comp, print_comp])
    
    try:
        await pipeline.run()
    except WebSocketDisconnect:
        pass
    except Exception as e:
        print(f"Transcription Pipeline encountered an error: {e}")
    finally:
        try:
            await pipeline.stop()
        except Exception:
            pass



